name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repository
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'linux/amd64,linux/arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: generate timestamp
      id: timestamp
      run: echo "::set-output name=date::$(date +'%s')"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: marcosvm/phantom:${{ steps.date.outputs.date }}
