name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repository
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          marcosvm/phantom
        tags: |
          type=raw,value={{sha}}
          type=raw,value={{date 'X'}}
          type=raw,value=latest
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: |
          linux/amd64
          linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
